### ISSUE TITLE
Full patch each time with files hosted on github

### ISSUE THREAD

**Issue by catapultam-habeo** [xackery/eqemupatcher#24]
Is there any way to avoid this? Hitting 'patch' always results in the entire payload being re-downloaded.

**Comment by xackery** [comment]
This has to do with a newline headache.. When you upload the contents to your eqemupatcher, your git is changing the line endings to \r\n for windows and I'm expecting \n, causing the CRCs to mismatch and trigger a download.

@catapultam-habeo  I assume each file is a .txt ?

**Comment by catapultam-habeo** [comment]
I'm actually using .gitattributes to force everything to be handled as binary, too many issues with corrupted s3d and similar.

-------- Original Message --------

**Comment by xackery** [comment]
I just ran your patcher, and you'll notice that the text files are being redownloaed after initial patch:
![image](https://user-images.githubusercontent.com/845670/230751857-83b6a87f-5db2-4ac9-b547-31ee4fc8e00d.png)

This is a sign the newline is not being honored properly, even if git attributes is set.

I'm not fully sure easiest fix.
You'll notice here:
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings

That eqemupatcher has set  in .gitattributes
```
* text eol=crlf
*.txt text
```

yet, if I go to your repo
```
> file eqhost.txt
eqhost.txt: ASCII text
```

the newline is set to \n, not \r\n for newline

Your .gitattributes was overwritten to `* text eol=auto`
https://github.com/Pyrelight-EQEMU/eqemupatcher/blob/master/.gitattributes#L4

This might be root cause.
It isn't truly forcing everything to be handled as binary.

What do you mean by corrupted s3d, though? With patcher?

**Comment by xackery** [comment]
I may look at making a fix on the CICD to resolve this, actually, at some point.
Basically, my theory is eqemupatcher (written in C#) is forcing things to use CRLF even if the file itself if LF.
CICD is running on linux, and the file uploaded is SUPPOSED to be crlf, but it obviously is not.. So, I'll force it on .txt files by replacing all line endings to \r\n. That should make CRC's match no matter how you upload them.

But I'll need to test and such. Thanks for bringing it up as a concern.

**Comment by catapultam-habeo** [comment]
'What do you mean by corrupted s3d, though? With patcher?'

Various binary files such as s3d, dll, etc, were not correctly surviving being committed and downloaded. 

Sorry, I'm vague on details right now because I backburnered this after fiddling on gitattributes until I got it to work well enough, then decided that it didn't work well enough.

I'm trying a few more things with gitattributes to see where I can get.

**Comment by catapultam-habeo** [comment]
I was able to get this to work as expected with this .gitattributes
https://github.com/Pyrelight-EQEMU/eqemupatcher/blob/master/.gitattributes

**Comment by xackery** [comment]
> I was able to get this to work as expected with this .gitattributes https://github.com/Pyrelight-EQEMU/eqemupatcher/blob/master/.gitattributes

Do you know if the crlf was the fix, or if it needed the txt = binary stuff?
I'll put it up on the main branch for other people's benefit if you sorted root cause

**Comment by catapultam-habeo** [comment]
The binary directives were required.

Sent from Proton Mail mobile

-------- Original Message --------
